controller:
  podAnnotations: {
   consul.hashicorp.com/connect-inject: "true",
   consul.hashicorp.com/connect-service: "ingress-nginx",
   consul.hashicorp.com/transparent-proxy: "true",
   consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,443",
   }
